services:
  whisperlive:
    build:
      context: .
      dockerfile: Dockerfile.jetson
      network: host
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - ALSA_CARD=Array
    network_mode: host
    devices:
      - /dev/snd:/dev/snd  # Maps all sound cards/mics
    volumes:
      - /etc/asound.conf:/etc/asound.conf:ro  # share host ALSA config
      - ${HOME}/WhisperLive:/app
    group_add:
      - audio
